# -*- coding: utf-8 -*-
"""PythonPractice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mF1UXuVHo05KRLbqODT9cagidoqwDe4v
"""

# Reverse a number
n=int(input("Enter a number:"))
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
print("The reverse of the number:",rev)

#Check if a no is palindrome
n=int(input("Enter a number:"))
a=str(n)
if a==a[::-1]:
  print("The number is a palindrome")
else:
  print("The number is not a palindrome")

#Factorial of n
n=int(input("Enter a number:"))
fact=1
for i in range(1,n+1):
  fact=fact*i
print("The factorial of",n,"is",fact)

